name: Push to Replicate

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest-8-cores
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Cog
        run: |
          sudo curl -o /usr/local/bin/cog -L https://github.com/replicate/cog/releases/latest/download/cog_Linux_x86_64
          sudo chmod +x /usr/local/bin/cog

      - name: Push to Replicate
        run: |
          cog login --token-stdin <<< "$REPLICATE_API_TOKEN"
          cog push r8.im/zaiontsevcanada-lab/depth-pro-raw
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
